# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/rhino/Desktop/Piano_Project/Piano_Project.cache/wt [current_project]
set_property parent.project_path C:/Users/rhino/Desktop/Piano_Project/Piano_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/rhino/Desktop/Piano_Project/Piano_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/sources_1/new/Clock_Slowdown.vhd
  C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/sources_1/new/JK_Flip_Flop_clear.vhd
  C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/sources_1/new/Octave_State.vhd
  C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/sources_1/new/Piano_Final.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/constrs_1/new/Ex5.xdc
set_property used_in_implementation false [get_files C:/Users/rhino/Desktop/Piano_Project/Piano_Project.srcs/constrs_1/new/Ex5.xdc]


synth_design -top Piano_Final -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Piano_Final.dcp

catch { report_utilization -file Piano_Final_utilization_synth.rpt -pb Piano_Final_utilization_synth.pb }
